'when creating an account, the user can chose between "person" and "company"'
@startuml
skinparam actorStyle awesome
:User: --> (person)
:User: --> (company)
@enduml

'Regardless of the type of the account, the user has a few actions he can take to personalise his account'
@startuml
skinparam actorStyle awesome
package Account as p{
  usecase "change Name" as uc1
  usecase "edit Biography" as uc2
  usecase "edit website" as uc3
  usecase "delete account" as uc4
}
:User: --> p
p --> uc1
p --> uc2
p --> uc3
p --> uc4
@enduml

@startuml
skinparam actorStyle awesome
package Gear as g{
  usecase "change name" as uc1
  usecase "edit image" as uc2
  usecase "remove gear" as uc3
  usecase "add gear" as uc4
}
:Company: --> g
g --> uc1
g --> uc2
g --> uc3
g --> uc4
@enduml
