@startuml

class Account {
- id: Long
- biography: String
- website: String
}

class Company {
- name: String
- projects: List<Project>
- inventory: List<Gear>
- vacancies: List<Vacancy>
}

class Project {
- name: String
- date: TimeRange
- gear: List<Gear>
- employee: List<Person>
- startTime: LocalDate
- endTime: LocalDate
}

class Gear {
- id: Long
- datesUsed: List<LocalDate>
- title: String
- image: int
}

class Person {
- firstName: String
- lastName: String
}

class Vacancy {
- id: Long
- title: String
- applicants: Person[]
- deadline: LocalDate
- opened: Boolean
}

class Message {
- id: Long
- source: Account
- destination: Account
- content: String
}

Account <|-- Company
Account <|-- Person
Company "1" -- "*" Project
Company "1" -- "*" Vacancy
Vacancy "*" -- "*"Person
Message "*" -- "2" Account
Project "0...1" -- "*" Gear
Gear "*" -- "1" Company
Project "*" -- "*" Person

@enduml
