@startuml

class Account {
- id: Long
- password: String
- email: String
- website: String
}

class Company {
- name: String
- address: String
- vacancies: List<Vacancy>
}

class Project {
- name: String
- date: TimeRange
- employees: List<Employee>
- company: Company
- startTime: LocalDate
- endTime: LocalDate
- vacancies: List<Vacancy>
}

class Person {
- firstName: String
- lastName: String
- birthdate: LocalDate
}

class Vacancy {
- id: Long
- title: String
- applicants: Person[]
- deadline: LocalDate
- opened: Boolean
}

class Message {
- id: Long
- source: Account
- destination: Account
- content: String
}

class Employee {
- id: Long
- person: Person
- company: Company
- isAdmin: Boolean
}

Account <|-- Company
Account <|-- Person
Company "1" -- "*" Project
Company "1" -- "*" Vacancy
Vacancy "*" -- "*"Person
Message "*" -- "2" Account
Project "*" -- "*" Person
Project "1" -- "*" Vacancy
Employee "*" -- "1" Company
Person "1" -- "*" Employee
@enduml
