@startuml
class Account {
- id: Int
}
class Company {
- name: String
- projects: List<Project>
- inventory: List<Gear>
}

class Project {
- name: String
- date: TimeRange
- vacancies: Vacancy[]
- gear: Gear[]
- employee: Person[]
}

class Gear {
- datesUsed: List<TimeRange>
- title: String
}

class TimeRange {
- startTime: LocalDate
- endTime: LocalDate
}

class Person {
- firstName: String
- lastName: String
}
class Vacancy {
- title: String
- applicants: Applicant[]
- deadline: LocalDate
- opened: Boolean
}
class Message {
- source: Account
- destination: Account
}

Account <|-- Company
Account <|-- Person
Company "1" -- "*" Project
Company "1" -- "*" Vacancy
Vacancy "*" -- "*"Person
Message "*" -- "2" Account
Project "*" -- "*" Gear
Project "1" -- "1" TimeRange
Gear "1" -- "*" TimeRange

@enduml
